export const ERROR_CODES = {
  // Authentication & Authorization
  UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
  FORBIDDEN: 'AUTH_FORBIDDEN',
  INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',

  // Validation
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_MAC_ADDRESS: 'INVALID_MAC_ADDRESS',
  INVALID_PHONE_NUMBER: 'INVALID_PHONE_NUMBER',

  // Resource Not Found
  PLAN_NOT_FOUND: 'PLAN_NOT_FOUND',
  CUSTOMER_NOT_FOUND: 'CUSTOMER_NOT_FOUND',
  PAYMENT_NOT_FOUND: 'PAYMENT_NOT_FOUND',
  VOUCHER_NOT_FOUND: 'VOUCHER_NOT_FOUND',
  ROUTER_NOT_FOUND: 'ROUTER_NOT_FOUND',
  SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',

  // Payments & Daraja
  PAYMENT_INITIATION_FAILED: 'PAYMENT_INITIATION_FAILED',
  PAYMENT_TIMEOUT: 'PAYMENT_TIMEOUT',
  PAYMENT_DECLINED: 'PAYMENT_DECLINED',
  PAYMENT_ALREADY_SETTLED: 'PAYMENT_ALREADY_SETTLED',
  DUPLICATE_TRANSACTION: 'DUPLICATE_TRANSACTION',

  // Vouchers
  VOUCHER_ALREADY_USED: 'VOUCHER_ALREADY_USED',
  VOUCHER_EXPIRED: 'VOUCHER_EXPIRED',
  VOUCHER_DISABLED: 'VOUCHER_DISABLED',

  // Network & Gateway
  ROUTER_UNREACHABLE: 'ROUTER_UNREACHABLE',
  RADIUS_DISCONNECT_FAILED: 'RADIUS_DISCONNECT_FAILED',
  CONCURRENT_DEVICE_LIMIT_REACHED: 'CONCURRENT_DEVICE_LIMIT_REACHED',

  // Server
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

export const REGEX_PATTERNS = {
  // Matches any valid MAC address with :, -, or no delimiter
  MAC_ADDRESS: /^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$/,
  // Matches Kenyan phone numbers: 07..., 01..., 2547..., 2541..., +254...
  KENYAN_PHONE: /^(?:\+?254|0)?([17]\d{8})$/,
};
